Repository GSM-GOGO/GSM-GOGO-Client, pull requests merged in 2024-03, with the labels that each got.

#1 [#1] 로그인 페이지를 퍼블리싱 했습니다.
  package.json
  src/App.tsx
  src/Pages/Signin/index.tsx
  src/Pages/Signin/style.ts
  src/assets/index.ts
  src/assets/png/SignInLogo.png
  src/assets/png/index.ts
  src/assets/svg/index.ts
  src/main.tsx
  yarn.lock
Labels: 🎨 Type: Publishing, 2️⃣ Priortiy: Medium

#2 [#2] 회원가입 페이지를 퍼블리싱 했습니다.
  package-lock.json
  package.json
  src/App.tsx
  src/Pages/Signup/index.tsx
  src/Pages/Signup/style.ts
  src/Pages/index.ts
  src/assets/svg/Logo.tsx
  src/assets/svg/index.ts
  src/components/Input/index.tsx
  src/components/Input/style.ts
  src/components/Timer/index.tsx
  src/types/FormDataType.ts
  yarn.lock
Labels: 🎨 Type: Publishing, 2️⃣ Priortiy: Medium

#5 [#5] 로그인 페이지의 퍼블리싱의 오류를 수정했습니다.
  package-lock.json
  package.json
  src/Pages/Signin/index.tsx
  src/Pages/Signin/style.ts
  src/assets/index.ts
  src/assets/svg/GAuthLogo.tsx
  src/assets/svg/index.ts
  src/main.tsx
  src/utils/env.ts
  yarn.lock
Labels: ⚡Type: Simple, 🐞 Type: Bug

#8 [#5] 로그인 로직과 메인 화면 퍼블리싱 뼈대를 제작 했습니다.
  package.json
  src/App.tsx
  src/Pages/Category/Basketball/index.tsx
  src/Pages/Category/Basketball/style.ts
  src/Pages/Category/Soccer/index.tsx
  src/Pages/Category/Soccer/style.ts
  src/Pages/Category/Volleyball/index.tsx
  src/Pages/Category/Volleyball/style.ts
  src/Pages/Signin/index.tsx
  src/Pages/Signin/style.ts
  src/assets/png/SignInLogo.png
  src/assets/svg/GAuthLogo.tsx
  src/utils/IsLoggedIn.ts
  src/utils/apis/auth.ts
  src/utils/env.ts
  src/utils/libs/apiClient.ts
  yarn.lock
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API

#11 [#11] 매치 리스트 화면을 퍼블리싱 했습니다.
  src/Pages/Category/Soccer/index.tsx
  src/Pages/Category/Soccer/style.ts
  src/main.tsx
Labels: 🎨 Type: Publishing

#12 [#12] 카테고리를 제작 했습니다
  src/Pages/Category/Basketball/index.tsx
  src/Pages/Category/Basketball/style.ts
  src/Pages/Category/Soccer/index.tsx
  src/Pages/Category/Soccer/style.ts
  src/Pages/Category/Volleyball/index.tsx
  src/Pages/Category/Volleyball/style.ts
  src/Pages/Main/index.tsx
  src/Pages/Main/style.ts
  src/components/Category/index.tsx
  src/components/Category/style.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature

#20 [#20] 일반경기 form을 퍼블리싱 했습니다.
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/NomalForm/style.ts
  src/Pages/Ranking/index.tsx
  src/assets/svg/CloseReview.tsx
  src/assets/svg/OpenReview.tsx
  src/assets/svg/index.ts
Labels: 🎨 Type: Publishing

#21 [#21] 팀추가 버튼 추가 및 축구 배구 농구 페이지 통합
  src/App.tsx
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Nomal/style.ts
  src/Pages/Category/Soccer/index.tsx
  src/Pages/Category/Soccer/style.ts
  src/Pages/Category/Sports/index.tsx
  src/Pages/Category/Sports/style.ts
  src/Pages/Category/Volleyball/index.tsx
  src/Pages/Category/Volleyball/style.ts
  src/assets/svg/TeamAddButton.tsx
  src/assets/svg/index.ts
Labels: 🔨 Type: Refector, 🎨 Type: Publishing, ✨ Type: Feature

#25 [#25] 잘못된 퍼블리싱을 수정
  src/Pages/AuthCallBack/index.tsx
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Nomal/style.ts
  src/Pages/Category/Sports/style.ts
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/NomalForm/style.ts
  src/Pages/Main/index.tsx
  src/Pages/Signin/style.ts
  src/assets/svg/Logo.tsx
  src/components/Category/style.ts
  src/style/Globalstyles.ts
  src/utils/libs/apiClient.ts
Labels: 🎨 Type: Publishing

#27 [#27] 회원가입 로직과 로그아웃 로직을 만들었다
  src/Pages/Ranking/index.tsx
  src/Pages/Signup/index.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Input/index.tsx
  src/utils/libs/apiClient.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API

#30 [#30] 경기참가 구현 및 Search
  src/Pages/Register/Badminton/index.tsx
  src/Pages/Register/index.tsx
  src/Pages/Register/nomal.tsx
  src/Pages/Register/style.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API, 1️⃣ Priority: High

#33 [#32] access토큰이 없을 때 signin으로 리다이랙트 훅 제작
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Sports/index.tsx
  src/Pages/Formation/BadmintonForm/index.tsx
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/SoccerForm/index.tsx
  src/Pages/Formation/VolleyForm/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/Minigame/index.tsx
  src/Pages/Ranking/index.tsx
  src/Pages/Register/Badminton/index.tsx
  src/Pages/Register/Soccer/index.tsx
  src/Pages/Register/Volleyball/index.tsx
  src/Pages/Register/index.tsx
  src/hook/useAccessTokenCheck.tsx
  yarn.lock
Labels: ✨ Type: Feature

#34 [#34] 리프래쉬 로직과 일부 페이지 반응형 적용
  src/Pages/Category/Nomal/style.ts
  src/Pages/Category/Sports/style.ts
  src/Pages/Ranking/index.tsx
  src/Pages/Ranking/style.ts
  src/Pages/Signup/index.tsx
  src/components/Category/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/main.tsx
  src/utils/libs/apiClient.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API

#36 [#36] 로그아웃 로직을 제작 했다.
  src/components/Header/index.tsx
Labels: ✨ Type: Feature

#37 [#37] 로딩페이지를 퍼블리싱 했습니다
  src/App.tsx
  src/Pages/AuthCallBack/index.tsx
  src/assets/png/LoadingLogo.png
  src/assets/png/index.ts
  src/components/Loading/index.tsx
  src/components/Loading/style.ts
Labels: 🎨 Type: Publishing

#39 [#39] 일반 경기 폼의 반응형 제작
  src/Pages/Formation/NomalForm/style.ts
Labels: 🎨 Type: Publishing

#44 [#43] 잡다한 로직 제작
  src/App.tsx
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Nomal/style.ts
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/NomalForm/style.ts
  src/Pages/Main/style.ts
  src/Pages/Register/index.tsx
  src/Pages/Signin/index.tsx
  src/Pages/Signup/index.tsx
  src/components/Input/index.tsx
  yarn.lock
Labels: 📬 Type: API

#46 [#46] 에세스 토큰 유무 로직 수정
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Sports/index.tsx
  src/Pages/Formation/BadmintonForm/index.tsx
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/SoccerForm/index.tsx
  src/Pages/Formation/VolleyForm/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/Minigame/index.tsx
  src/Pages/Ranking/index.tsx
  src/Pages/Register/Badminton/index.tsx
  src/Pages/Register/Soccer/index.tsx
  src/Pages/Register/Volleyball/index.tsx
  src/Pages/Register/index.tsx
Labels: 📬 Type: API

#47 [#47] 빌드 오류 일부
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Formation/NomalForm/style.ts
  src/Pages/Ranking/index.tsx
  src/Pages/Register/Badminton/index.tsx
  src/Pages/Register/Soccer/index.tsx
  src/Pages/Register/Volleyball/index.tsx
  src/Pages/Register/index.tsx
  src/Pages/Register/nomal.tsx
  src/Pages/Signup/index.tsx
  src/components/Input/index.tsx
Labels: 🐞 Type: Bug, 1️⃣ Priority: High

#49 add resetNormalArr
  src/Pages/Register/nomal.tsx
Labels: 🐞 Type: Bug, 2️⃣ Priortiy: Medium

#54 [#54] 헤더 & 모달 문제 해결
  src/components/Header/style.ts
  src/components/HeaderContainer/style.ts
Labels: 🐞 Type: Bug
