Repository GSM-GOGO/GSM-GOGO-Client, pull requests merged in 2024-04, with the labels that each got.

#61 [#59] 리프래쉬 토큰 재발급 오류 수정
  src/utils/libs/apiClient.ts
Labels: 📬 Type: API, 0️⃣ Priority: Critical

#65 [#65] 토큰이 없지만 메인화면이 보이는 버그 수정
  src/App.tsx
  src/hook/useAuthenticate.ts
  src/utils/libs/PrivateRoute.tsx
Labels: 🪛 Type: Performance, 2️⃣ Priortiy: Medium

#66 [#65] 로그아웃 개선 & 축구 인원 변경
  src/Pages/Register/Soccer/index.tsx
  src/Pages/Register/index.tsx
  src/components/Header/index.tsx
Labels: 📬 Type: API, 3️⃣ Priority: Low

#67 [#67] 일반게임의 팔자 줄넘기를 추가함
  src/Pages/Formation/NomalForm/index.tsx
  src/Pages/Register/index.tsx
  src/Pages/Register/nomal.tsx
Labels: 🎨 Type: Publishing, 📬 Type: API

#68 [#68] 포에이션의 url을 params로 변경
  src/App.tsx
  src/Pages/Category/Sports/index.tsx
  src/Pages/Formation/BadmintonForm/index.tsx
  src/Pages/Formation/SoccerForm/index.tsx
  src/Pages/Formation/VolleyForm/index.tsx
Labels: ✨ Type: Feature

#70 [#70] 카테고리 스트로크 모바일 화면 수정
  src/Pages/Category/Nomal/index.tsx
  src/Pages/Category/Nomal/style.ts
  src/Pages/Category/Sports/index.tsx
  src/Pages/Category/Sports/style.ts
Labels: 🎨 Type: Publishing

#76 [#76] 코인 미니게임 추가
  src/App.tsx
  src/Pages/Minigame/CoinGame/index.tsx
  src/Pages/Minigame/CoinGame/style.ts
  src/Pages/Minigame/index.tsx
  src/Pages/Minigame/style.ts
  src/Pages/index.ts
  src/assets/png/HeadCoin.png
  src/assets/png/TailCoin.png
  src/assets/png/index.ts
  src/assets/svg/CoinIcon.tsx
  src/assets/svg/index.ts
  src/components/Header/index.tsx
  src/components/MiniGameCategory/index.tsx
  src/components/MiniGameCategory/style.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API

#74 [#73] 룰렛 추가
  src/App.tsx
  src/Pages/Minigame/Roulette/index.tsx
  src/Pages/Minigame/Roulette/style.ts
  src/assets/png/Roulette_point.png
  src/assets/png/Rouletteimg.png
  src/assets/png/index.ts
  src/assets/svg/Roulette.tsx
  src/assets/svg/index.ts
  src/components/Header/index.tsx
Labels: ✨ Type: Feature

#78 [#78] 선수가 출전한 경기의 로직을 추가 했습니다. (대진표 폴더 분할)
  src/App.tsx
  src/Pages/Bracket/BadmintonBracket/index.tsx
  src/Pages/Bracket/BadmintonBracket/style.ts
  src/Pages/Bracket/ScoccerBracket/index.tsx
  src/Pages/Bracket/ScoccerBracket/style.ts
  src/Pages/Bracket/VolleyballBracket/index.tsx
  src/Pages/Bracket/VolleyballBracket/style.ts
  src/components/MiniGameCategory/index.tsx
  src/components/PlayingContainer/index.tsx
Labels: 🎨 Type: Publishing, 📬 Type: API

#79 [#76] gsm gogo 2차 릴리즈 배포
  index.html
  src/App.tsx
  src/Pages/Bracket/BadmintonBracket/index.tsx
  src/Pages/Bracket/BadmintonBracket/style.ts
  src/Pages/Bracket/ScoccerBracket/index.tsx
  src/Pages/Bracket/ScoccerBracket/style.ts
  src/Pages/Bracket/VolleyballBracket/index.tsx
  src/Pages/Bracket/VolleyballBracket/style.ts
  src/Pages/Category/Sports/index.tsx
  src/Pages/Category/Sports/style.ts
  src/Pages/Main/index.tsx
  src/Pages/Main/style.ts
  src/Pages/Minigame/CoinGame/index.tsx
  src/Pages/Minigame/CoinGame/style.ts
  src/Pages/Minigame/Roulette/index.tsx
  src/Pages/Minigame/Roulette/style.ts
  src/Pages/Minigame/index.tsx
  src/Pages/Minigame/style.ts
  src/Pages/index.ts
  src/assets/png/BracketFramePng.png
  src/assets/png/HeadCoin.png
  src/assets/png/Roulette_point.png
  src/assets/png/Rouletteimg.png
  src/assets/png/TailCoin.png
  src/assets/png/index.ts
  src/assets/svg/BracketFrame.tsx
  src/assets/svg/CoinIcon.tsx
  src/assets/svg/Roulette.tsx
  src/assets/svg/index.ts
  src/components/Header/index.tsx
  src/components/MiniGameCategory/index.tsx
  src/components/MiniGameCategory/style.ts
  src/components/PlayingContainer/index.tsx
  src/components/PlayingContainer/style.ts
  src/components/WeatherContainer/index.tsx
  src/components/WeatherContainer/style.ts
  src/style/Bracket/style.ts
  sw.js
Labels: 🌏 Type: Deploy, 1️⃣ Priority: High
