Repository GSM-GOGO/GSM-GOGO-Client, pull requests merged in 2024-05, with the labels that each got.

#84 [#84] 마이페이지를 퍼블리싱 했습니다
  src/App.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/MyPage/style.ts
  src/assets/svg/DeleteIcon.tsx
  src/assets/svg/DisabledFilterIcon.tsx
  src/assets/svg/LogoutIcon.tsx
  src/assets/svg/MyPageIcon.tsx
  src/assets/svg/SelectFilterIcon.tsx
  src/assets/svg/Stroke.tsx
  src/assets/svg/ThreeDot.tsx
  src/assets/svg/index.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
Labels: 🎨 Type: Publishing, 2️⃣ Priortiy: Medium

#85 [#85] 마이페이지 로직을 완성 했습니다
  src/Pages/MyPage/index.tsx
  src/Pages/MyPage/style.ts
  src/assets/svg/NotMyPage.tsx
  src/assets/svg/index.ts
  src/components/Header/index.tsx
  src/components/MyPageFilter/index.tsx
  src/components/MyPageFilter/style.ts
  src/components/MyPageLogout/index.tsx
  src/components/MyPageLogout/style.ts
  src/types/MatchData.ts
  src/types/MyPageFilter.ts
  src/utils/libs/battingFilter.ts
  src/utils/libs/myPage.ts
Labels: 🎨 Type: Publishing, ✨ Type: Feature, 📬 Type: API, 2️⃣ Priortiy: Medium

#86 add main my betting
  src/components/PlayingContainer/index.tsx
  src/components/PlayingContainer/style.ts
  src/components/PlayingContainer/style1.ts
Labels: 0️⃣ Priority: Critical

#88 [#88] 마이페이지 필터를 수정 했습니다
  src/App.tsx
  src/Pages/MyPage/index.tsx
  src/components/Header/style.ts
Labels: 🎨 Type: Publishing, 🐞 Type: Bug, 1️⃣ Priority: High

#95 [#95] 버튼에 디바운스를 걸었습니다
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/Pages/Minigame/CoinGame/index.tsx
  src/Pages/Minigame/NunchiGame/index.tsx
  src/Pages/Minigame/Roulette/index.tsx
  src/components/PlayingContainer/index.tsx
  src/components/PlayingContainer/style.ts
  yarn.lock
Labels: 🐞 Type: Bug, 2️⃣ Priortiy: Medium

#96 [#96] 배드민턴 대진표를 업데이트 했습니다
  src/Pages/Bracket/VolleyballBracket/index.tsx
Labels: 🎨 Type: Publishing
